CREATE TABLE appointments
(
    appointment_id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    professional_professional_id BIGINT,
    client_client_id             BIGINT,
    date                         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_appointments PRIMARY KEY (appointment_id)
);

CREATE TABLE clients
(
    client_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_clients PRIMARY KEY (client_id)
);

CREATE TABLE clinics
(
    clinic_id       BIGINT       NOT NULL,
    name            VARCHAR(50)  NOT NULL,
    cnpj            VARCHAR(255) NOT NULL,
    address         VARCHAR(255),
    type_of_service VARCHAR(255),
    CONSTRAINT pk_clinics PRIMARY KEY (clinic_id)
);

CREATE TABLE legal_or_natural_person
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number VARCHAR(255),
    image_url    VARCHAR(255),
    CONSTRAINT pk_legalornaturalperson PRIMARY KEY (id)
);

CREATE TABLE persons
(
    person_id  BIGINT       NOT NULL,
    first_name VARCHAR(30)  NOT NULL,
    last_name  VARCHAR(50)  NOT NULL,
    cpf        VARCHAR(255) NOT NULL,
    gender     VARCHAR(255),
    CONSTRAINT pk_persons PRIMARY KEY (person_id)
);

CREATE TABLE professionals
(
    professional_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    crp             VARCHAR(255),
    approach        VARCHAR(255),
    clinic_id       BIGINT,
    description     VARCHAR(500),
    person_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_professionals PRIMARY KEY (professional_id)
);

ALTER TABLE users
    ADD legal_or_natural_person_id BIGINT;

ALTER TABLE appointments
    ADD CONSTRAINT FK_APPOINTMENTS_ON_CLIENT_CLIENT FOREIGN KEY (client_client_id) REFERENCES clients (client_id);

ALTER TABLE appointments
    ADD CONSTRAINT FK_APPOINTMENTS_ON_PROFESSIONAL_PROFESSIONAL FOREIGN KEY (professional_professional_id) REFERENCES professionals (professional_id);

ALTER TABLE clients
    ADD CONSTRAINT FK_CLIENTS_ON_PERSON FOREIGN KEY (person_id) REFERENCES persons (person_id);

ALTER TABLE clinics
    ADD CONSTRAINT FK_CLINICS_ON_CLINIC FOREIGN KEY (clinic_id) REFERENCES legal_or_natural_person (id);

ALTER TABLE persons
    ADD CONSTRAINT FK_PERSONS_ON_PERSON FOREIGN KEY (person_id) REFERENCES legal_or_natural_person (id);

ALTER TABLE professionals
    ADD CONSTRAINT FK_PROFESSIONALS_ON_CLINIC FOREIGN KEY (clinic_id) REFERENCES clinics (clinic_id);

ALTER TABLE professionals
    ADD CONSTRAINT FK_PROFESSIONALS_ON_PERSON FOREIGN KEY (person_id) REFERENCES persons (person_id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_LEGALORNATURALPERSON FOREIGN KEY (legal_or_natural_person_id) REFERENCES legal_or_natural_person (id);